### ISSUE TITLE
making codebase work for alignment group

### ISSUE THREAD

**Issue by riensou** [in-context-learning-2024/in-context#45]
- [ ] finalize LoRA pull request #33 
- [ ] complete Chebyshev polynomial (function class and context model) pull request #29 
- [ ] finish to do evaluation and benchmarks #27 
- [ ] add wrappers capability along with threshold wrapper to simulate alignment #44
